// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using RayEngine;
//
//    var world = World.FromJson(jsonString);

namespace RayEngine
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class World
    {
        [JsonProperty("__header__")]
        public Header Header { get; set; }

        [JsonProperty("iid")]
        public Guid Iid { get; set; }

        [JsonProperty("jsonVersion")]
        public string JsonVersion { get; set; }

        [JsonProperty("appBuildId")]
        public long AppBuildId { get; set; }

        [JsonProperty("nextUid")]
        public long NextUid { get; set; }

        [JsonProperty("identifierStyle")]
        public string IdentifierStyle { get; set; }

        [JsonProperty("toc")]
        public List<object> Toc { get; set; }

        [JsonProperty("worldLayout")]
        public object WorldLayout { get; set; }

        [JsonProperty("worldGridWidth")]
        public object WorldGridWidth { get; set; }

        [JsonProperty("worldGridHeight")]
        public object WorldGridHeight { get; set; }

        [JsonProperty("defaultLevelWidth")]
        public object DefaultLevelWidth { get; set; }

        [JsonProperty("defaultLevelHeight")]
        public object DefaultLevelHeight { get; set; }

        [JsonProperty("defaultPivotX")]
        public long DefaultPivotX { get; set; }

        [JsonProperty("defaultPivotY")]
        public long DefaultPivotY { get; set; }

        [JsonProperty("defaultGridSize")]
        public long DefaultGridSize { get; set; }

        [JsonProperty("defaultEntityWidth")]
        public long DefaultEntityWidth { get; set; }

        [JsonProperty("defaultEntityHeight")]
        public long DefaultEntityHeight { get; set; }

        [JsonProperty("bgColor")]
        public string BgColor { get; set; }

        [JsonProperty("defaultLevelBgColor")]
        public string DefaultLevelBgColor { get; set; }

        [JsonProperty("minifyJson")]
        public bool MinifyJson { get; set; }

        [JsonProperty("externalLevels")]
        public bool ExternalLevels { get; set; }

        [JsonProperty("exportTiled")]
        public bool ExportTiled { get; set; }

        [JsonProperty("simplifiedExport")]
        public bool SimplifiedExport { get; set; }

        [JsonProperty("imageExportMode")]
        public string ImageExportMode { get; set; }

        [JsonProperty("exportLevelBg")]
        public bool ExportLevelBg { get; set; }

        [JsonProperty("pngFilePattern")]
        public object PngFilePattern { get; set; }

        [JsonProperty("backupOnSave")]
        public bool BackupOnSave { get; set; }

        [JsonProperty("backupLimit")]
        public long BackupLimit { get; set; }

        [JsonProperty("backupRelPath")]
        public object BackupRelPath { get; set; }

        [JsonProperty("levelNamePattern")]
        public string LevelNamePattern { get; set; }

        [JsonProperty("tutorialDesc")]
        public object TutorialDesc { get; set; }

        [JsonProperty("customCommands")]
        public List<object> CustomCommands { get; set; }

        [JsonProperty("flags")]
        public List<string> Flags { get; set; }

        [JsonProperty("defs")]
        public Defs Defs { get; set; }

        [JsonProperty("levels")]
        public List<object> Levels { get; set; }

        [JsonProperty("worlds")]
        public List<WorldElement> Worlds { get; set; }

        [JsonProperty("dummyWorldIid")]
        public Guid DummyWorldIid { get; set; }
    }

    public partial class Defs
    {
        [JsonProperty("layers")]
        public List<Layer> Layers { get; set; }

        [JsonProperty("entities")]
        public List<Entity> Entities { get; set; }

        [JsonProperty("tilesets")]
        public List<Tileset> Tilesets { get; set; }

        [JsonProperty("enums")]
        public List<object> Enums { get; set; }

        [JsonProperty("externalEnums")]
        public List<object> ExternalEnums { get; set; }

        [JsonProperty("levelFields")]
        public List<object> LevelFields { get; set; }
    }

    public partial class Entity
    {
        [JsonProperty("identifier")]
        public string Identifier { get; set; }

        [JsonProperty("uid")]
        public long Uid { get; set; }

        [JsonProperty("tags")]
        public List<object> Tags { get; set; }

        [JsonProperty("exportToToc")]
        public bool ExportToToc { get; set; }

        [JsonProperty("allowOutOfBounds")]
        public bool AllowOutOfBounds { get; set; }

        [JsonProperty("doc")]
        public object Doc { get; set; }

        [JsonProperty("width")]
        public long Width { get; set; }

        [JsonProperty("height")]
        public long Height { get; set; }

        [JsonProperty("resizableX")]
        public bool ResizableX { get; set; }

        [JsonProperty("resizableY")]
        public bool ResizableY { get; set; }

        [JsonProperty("minWidth")]
        public object MinWidth { get; set; }

        [JsonProperty("maxWidth")]
        public object MaxWidth { get; set; }

        [JsonProperty("minHeight")]
        public object MinHeight { get; set; }

        [JsonProperty("maxHeight")]
        public object MaxHeight { get; set; }

        [JsonProperty("keepAspectRatio")]
        public bool KeepAspectRatio { get; set; }

        [JsonProperty("tileOpacity")]
        public long TileOpacity { get; set; }

        [JsonProperty("fillOpacity")]
        public long FillOpacity { get; set; }

        [JsonProperty("lineOpacity")]
        public long LineOpacity { get; set; }

        [JsonProperty("hollow")]
        public bool Hollow { get; set; }

        [JsonProperty("color")]
        public string Color { get; set; }

        [JsonProperty("renderMode")]
        public string RenderMode { get; set; }

        [JsonProperty("showName")]
        public bool ShowName { get; set; }

        [JsonProperty("tilesetId")]
        public object TilesetId { get; set; }

        [JsonProperty("tileRenderMode")]
        public string TileRenderMode { get; set; }

        [JsonProperty("tileRect")]
        public object TileRect { get; set; }

        [JsonProperty("uiTileRect")]
        public object UiTileRect { get; set; }

        [JsonProperty("nineSliceBorders")]
        public List<object> NineSliceBorders { get; set; }

        [JsonProperty("maxCount")]
        public long MaxCount { get; set; }

        [JsonProperty("limitScope")]
        public string LimitScope { get; set; }

        [JsonProperty("limitBehavior")]
        public string LimitBehavior { get; set; }

        [JsonProperty("pivotX")]
        public long PivotX { get; set; }

        [JsonProperty("pivotY")]
        public long PivotY { get; set; }

        [JsonProperty("fieldDefs")]
        public List<object> FieldDefs { get; set; }
    }

    public partial class Layer
    {
        [JsonProperty("__type")]
        public string Type { get; set; }

        [JsonProperty("identifier")]
        public string Identifier { get; set; }

        [JsonProperty("type")]
        public string LayerType { get; set; }

        [JsonProperty("uid")]
        public long Uid { get; set; }

        [JsonProperty("doc")]
        public object Doc { get; set; }

        [JsonProperty("uiColor")]
        public object UiColor { get; set; }

        [JsonProperty("gridSize")]
        public long GridSize { get; set; }

        [JsonProperty("guideGridWid")]
        public long GuideGridWid { get; set; }

        [JsonProperty("guideGridHei")]
        public long GuideGridHei { get; set; }

        [JsonProperty("displayOpacity")]
        public long DisplayOpacity { get; set; }

        [JsonProperty("inactiveOpacity")]
        public long InactiveOpacity { get; set; }

        [JsonProperty("hideInList")]
        public bool HideInList { get; set; }

        [JsonProperty("hideFieldsWhenInactive")]
        public bool HideFieldsWhenInactive { get; set; }

        [JsonProperty("canSelectWhenInactive")]
        public bool CanSelectWhenInactive { get; set; }

        [JsonProperty("renderInWorldView")]
        public bool RenderInWorldView { get; set; }

        [JsonProperty("pxOffsetX")]
        public long PxOffsetX { get; set; }

        [JsonProperty("pxOffsetY")]
        public long PxOffsetY { get; set; }

        [JsonProperty("parallaxFactorX")]
        public long ParallaxFactorX { get; set; }

        [JsonProperty("parallaxFactorY")]
        public long ParallaxFactorY { get; set; }

        [JsonProperty("parallaxScaling")]
        public bool ParallaxScaling { get; set; }

        [JsonProperty("requiredTags")]
        public List<object> RequiredTags { get; set; }

        [JsonProperty("excludedTags")]
        public List<object> ExcludedTags { get; set; }

        [JsonProperty("autoTilesKilledByOtherLayerUid")]
        public object AutoTilesKilledByOtherLayerUid { get; set; }

        [JsonProperty("uiFilterTags")]
        public List<object> UiFilterTags { get; set; }

        [JsonProperty("useAsyncRender")]
        public bool UseAsyncRender { get; set; }

        [JsonProperty("intGridValues")]
        public List<object> IntGridValues { get; set; }

        [JsonProperty("intGridValuesGroups")]
        public List<object> IntGridValuesGroups { get; set; }

        [JsonProperty("autoRuleGroups")]
        public List<object> AutoRuleGroups { get; set; }

        [JsonProperty("autoSourceLayerDefUid")]
        public object AutoSourceLayerDefUid { get; set; }

        [JsonProperty("tilesetDefUid")]
        public long TilesetDefUid { get; set; }

        [JsonProperty("tilePivotX")]
        public long TilePivotX { get; set; }

        [JsonProperty("tilePivotY")]
        public long TilePivotY { get; set; }

        [JsonProperty("biomeFieldUid")]
        public object BiomeFieldUid { get; set; }
    }

    public partial class Tileset
    {
        [JsonProperty("__cWid")]
        public long CWid { get; set; }

        [JsonProperty("__cHei")]
        public long CHei { get; set; }

        [JsonProperty("identifier")]
        public string Identifier { get; set; }

        [JsonProperty("uid")]
        public long Uid { get; set; }

        [JsonProperty("relPath")]
        public string RelPath { get; set; }

        [JsonProperty("embedAtlas")]
        public object EmbedAtlas { get; set; }

        [JsonProperty("pxWid")]
        public long PxWid { get; set; }

        [JsonProperty("pxHei")]
        public long PxHei { get; set; }

        [JsonProperty("tileGridSize")]
        public long TileGridSize { get; set; }

        [JsonProperty("spacing")]
        public long Spacing { get; set; }

        [JsonProperty("padding")]
        public long Padding { get; set; }

        [JsonProperty("tags")]
        public List<object> Tags { get; set; }

        [JsonProperty("tagsSourceEnumUid")]
        public object TagsSourceEnumUid { get; set; }

        [JsonProperty("enumTags")]
        public List<object> EnumTags { get; set; }

        [JsonProperty("customData")]
        public List<object> CustomData { get; set; }

        [JsonProperty("savedSelections")]
        public List<object> SavedSelections { get; set; }

        [JsonProperty("cachedPixelData")]
        public CachedPixelData CachedPixelData { get; set; }
    }

    public partial class CachedPixelData
    {
        [JsonProperty("opaqueTiles")]
        public string OpaqueTiles { get; set; }

        [JsonProperty("averageColors")]
        public string AverageColors { get; set; }
    }

    public partial class Header
    {
        [JsonProperty("fileType")]
        public string FileType { get; set; }

        [JsonProperty("app")]
        public string App { get; set; }

        [JsonProperty("doc")]
        public Uri Doc { get; set; }

        [JsonProperty("schema")]
        public Uri Schema { get; set; }

        [JsonProperty("appAuthor")]
        public string AppAuthor { get; set; }

        [JsonProperty("appVersion")]
        public string AppVersion { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }
    }

    public partial class WorldElement
    {
        [JsonProperty("iid")]
        public Guid Iid { get; set; }

        [JsonProperty("identifier")]
        public string Identifier { get; set; }

        [JsonProperty("defaultLevelWidth")]
        public long DefaultLevelWidth { get; set; }

        [JsonProperty("defaultLevelHeight")]
        public long DefaultLevelHeight { get; set; }

        [JsonProperty("worldGridWidth")]
        public long WorldGridWidth { get; set; }

        [JsonProperty("worldGridHeight")]
        public long WorldGridHeight { get; set; }

        [JsonProperty("worldLayout")]
        public string WorldLayout { get; set; }

        [JsonProperty("levels")]
        public List<Level> Levels { get; set; }
    }

    public partial class Level
    {
        [JsonProperty("identifier")]
        public string Identifier { get; set; }

        [JsonProperty("iid")]
        public Guid Iid { get; set; }

        [JsonProperty("uid")]
        public long Uid { get; set; }

        [JsonProperty("worldX")]
        public long WorldX { get; set; }

        [JsonProperty("worldY")]
        public long WorldY { get; set; }

        [JsonProperty("worldDepth")]
        public long WorldDepth { get; set; }

        [JsonProperty("pxWid")]
        public long PxWid { get; set; }

        [JsonProperty("pxHei")]
        public long PxHei { get; set; }

        [JsonProperty("__bgColor")]
        public string BgColor { get; set; }

        [JsonProperty("bgColor")]
        public object LevelBgColor { get; set; }

        [JsonProperty("useAutoIdentifier")]
        public bool UseAutoIdentifier { get; set; }

        [JsonProperty("bgRelPath")]
        public object BgRelPath { get; set; }

        [JsonProperty("bgPos")]
        public object LevelBgPos { get; set; }

        [JsonProperty("bgPivotX")]
        public double BgPivotX { get; set; }

        [JsonProperty("bgPivotY")]
        public double BgPivotY { get; set; }

        [JsonProperty("__smartColor")]
        public string SmartColor { get; set; }

        [JsonProperty("__bgPos")]
        public object BgPos { get; set; }

        [JsonProperty("externalRelPath")]
        public object ExternalRelPath { get; set; }

        [JsonProperty("fieldInstances")]
        public List<object> FieldInstances { get; set; }

        [JsonProperty("layerInstances")]
        public List<LayerInstance> LayerInstances { get; set; }

        [JsonProperty("__neighbours")]
        public List<object> Neighbours { get; set; }
    }

    public partial class LayerInstance
    {
        [JsonProperty("__identifier")]
        public string Identifier { get; set; }

        [JsonProperty("__type")]
        public string Type { get; set; }

        [JsonProperty("__cWid")]
        public long CWid { get; set; }

        [JsonProperty("__cHei")]
        public long CHei { get; set; }

        [JsonProperty("__gridSize")]
        public long GridSize { get; set; }

        [JsonProperty("__opacity")]
        public long Opacity { get; set; }

        [JsonProperty("__pxTotalOffsetX")]
        public long PxTotalOffsetX { get; set; }

        [JsonProperty("__pxTotalOffsetY")]
        public long PxTotalOffsetY { get; set; }

        [JsonProperty("__tilesetDefUid")]
        public long TilesetDefUid { get; set; }

        [JsonProperty("__tilesetRelPath")]
        public string TilesetRelPath { get; set; }

        [JsonProperty("iid")]
        public Guid Iid { get; set; }

        [JsonProperty("levelId")]
        public long LevelId { get; set; }

        [JsonProperty("layerDefUid")]
        public long LayerDefUid { get; set; }

        [JsonProperty("pxOffsetX")]
        public long PxOffsetX { get; set; }

        [JsonProperty("pxOffsetY")]
        public long PxOffsetY { get; set; }

        [JsonProperty("visible")]
        public bool Visible { get; set; }

        [JsonProperty("optionalRules")]
        public List<object> OptionalRules { get; set; }

        [JsonProperty("intGridCsv")]
        public List<object> IntGridCsv { get; set; }

        [JsonProperty("autoLayerTiles")]
        public List<object> AutoLayerTiles { get; set; }

        [JsonProperty("seed")]
        public long Seed { get; set; }

        [JsonProperty("overrideTilesetUid")]
        public object OverrideTilesetUid { get; set; }

        [JsonProperty("gridTiles")]
        public List<GridTile> GridTiles { get; set; }

        [JsonProperty("entityInstances")]
        public List<object> EntityInstances { get; set; }
    }

    public partial class GridTile
    {
        [JsonProperty("px")]
        public List<long> Px { get; set; }

        [JsonProperty("src")]
        public List<long> Src { get; set; }

        [JsonProperty("f")]
        public long F { get; set; }

        [JsonProperty("t")]
        public long T { get; set; }

        [JsonProperty("d")]
        public List<long> D { get; set; }

        [JsonProperty("a")]
        public long A { get; set; }
    }

    public partial class World
    {
        public static World FromJson(string json) => JsonConvert.DeserializeObject<World>(json, RayEngine.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this World self) => JsonConvert.SerializeObject(self, RayEngine.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
